version: "3.2"
networks:
  northwind:
    driver: bridge  
services:
  mysql:
    container_name: lambdaorm-svc-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=northwind
      - MYSQL_PASSWORD=northwind
      - MYSQL_ROOT_PASSWORD=northwind
    ports:
      - '3308:3306'
    expose:
      - 3308
    networks:
      - northwind
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql  
  lambdaorm-api:
    depends_on:
      - mysql
    container_name: lambdaorm-svc-api
    image: flaviorita/lambdaorm-svc:0.8.36
    restart: always  
    environment:
      HOST: http://0.0.0.0
      PORT: 9292
      REQUEST_BODY_SIZE: 100mb
      RATE_LIMIT_WINDOWS_MS: 60000
      RATE_LIMIT_MAX: 1000
      WORKSPACE: /workspace
      MYSQL_CNX: '{"host":"http://mysql","port":3308,"user":"northwind","password":"northwind","database":"northwind","multipleStatements": true ,"waitForConnections": true }'
    ports:
      - '9292:9292'
    expose:
      - 9292  
    networks:
      - northwind
    volumes:
      - ./workspace:/workspace    
volumes:
  mysql-data:
  mysql-log: 
