version: "3.2"
# networks:
#   svclab:
#     driver: bridge    
services:
  postgres:
    container_name: lambdaorm-svc-postgres
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=northwind    
      - POSTGRES_USER=northwind
      - POSTGRES_PASSWORD=northwind
    # volumes:
    #   - ./volume/postgres-data:/var/lib/postgresql/data
    #   - ./db/postgres/startup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5436:5432'
    expose:
      - 5436  
    # networks:
    #   - svclab 
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
  mySql:
    container_name: lambdaorm-svc-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=northwind
      - MYSQL_PASSWORD=northwind
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    # volumes:
    #   - ./volume/MySQL:/var/lib/mysql
    ports:
      - '3309:3306'
    expose:
      - 3309  
    # networks:
    #   - svclab     
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10    
  lambdaorm-api:
    depends_on:
      - postgres
      - mySql
    container_name: lambdaorm-svc-api
    # image: flaviorita/lambdaorm-svc:0.4.40
    build:
      context: ./../../../../
    restart: always  
    environment:
      - HOST=http://localhost
      - PORT=9292
      - WORKSPACE=/workspace
      - CNN_POSTGRES={"host":"postgres","port":5436,"user":"northwind","password":"northwind","database":"northwind"}
      - CNN_MYSQL={"host":"mySql","port":3309,"user":"northwind","password":"northwind","database":"northwind"}
    ports:
      - 9292:9292
    expose:
      - 9292
    # networks:
    #   - svclab  
    volumes:
      - ./workspace:/workspace  
