@host = http://localhost:9293
@keycloaHost = http://localhost:8180


### General -------------------------------------------------------------------------------------------------------------------------

### ping
GET {{host}}/ping HTTP/1.1

### health
GET {{host}}/health HTTP/1.1

### metrics
GET {{host}}/metrics HTTP/1.1

### metrics prometheus
GET {{host}}/actuator/prometheus HTTP/1.1

### Schema  -------------------------------------------------------------------------------------------------------------------------

### entities
GET {{host}}/entities HTTP/1.1
content-type: application/json

### entity
GET {{host}}/entities/PmParties HTTP/1.1
content-type: application/json

### stages
GET {{host}}/stages HTTP/1.1
content-type: application/json

### stage
GET {{host}}/stages/default HTTP/1.1
content-type: application/json

### queries -------------------------------------------------------------------------------------------------------------------------

@options = {"stage":"default" }
@query=PmIndividuals.filter(p=> p.gender == gender).include(p->p.party)
@data={"gender":"F"}

### Model
POST {{host}}/model HTTP/1.1
content-type: application/json

{	
	"query": "{{query}}"
}

### Parameters
POST {{host}}/parameters HTTP/1.1
content-type: application/json

{	
	"query": "{{query}}"
}

### Metadata
POST {{host}}/metadata HTTP/1.1
content-type: application/json

{	
	"query": "{{query}}"
}

### Constraints
POST {{host}}/constraints HTTP/1.1
content-type: application/json

{	
	"query": "PmIndividuals.bulkInsert().include(p=>p.party.include(p=> [p.identifications,p.contactMediums]))"
}

### Sentence
POST {{host}}/sentence HTTP/1.1
content-type: application/json

{
	"options": {{options}},
	"query": "{{query}}"
}

### Execute
POST {{host}}/execute HTTP/1.1
content-type: application/json

{
	"options": {{options}},
	"query": "{{query}}",
	"data":{{data}}
}

### Execute Queued
POST {{host}}/execute-queued HTTP/1.1
content-type: application/json

{
	"options":{{options}},
	"query": "{{query}}",
	"data":{{data}},
	"topic":"test-execute",
	"chunk": 10 
}