@host = http://localhost:9291
@keycloaHost = http://localhost:8180
@locStage = PostgreSQL
# @locStage = localOracle
@realm = cclp



### General -------------------------------------------------------------------------------------------------------------------------

### ping
GET {{host}}/ping HTTP/1.1

### health
GET {{host}}/health HTTP/1.1

### metrics
GET {{host}}/metrics HTTP/1.1

### Metadata -------------------------------------------------------------------------------------------------------------------------

### Schema.entities
GET {{host}}/schema/entities HTTP/1.1
content-type: application/json

{
}

### stages
GET {{host}}/stage HTTP/1.1
content-type: application/json

{
}

### Sentence
POST {{host}}/expression/sentence?stage={{locStage}} HTTP/1.1
content-type: application/json

{
	"expression": "PmIndividuals.include(p->p.party)",
	"data":{}
}

### Execute
POST {{host}}/expression/execute?stage={{locStage}} HTTP/1.1
content-type: application/json

{
	"expression": "LocAreaTypes.include(p => p.areas)",
	"data":{}
}