version: "3"
networks:
  pentest:
    driver: bridge
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=northwind    
      - POSTGRES_USER=northwind
      - POSTGRES_PASSWORD=northwind
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # expose:
    #   - 5435  
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "northwind" ]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - pentest
  orm:
    depends_on:
      - postgres
    container_name: orm
    image: flaviorita/lambdaorm-svc:0.6.2
    # build:
    #   context: ./../../../../
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 250M
        reservations:
          cpus: '0.05'
          memory: 250M  
    environment:
      - HOST=http://0.0.0.0
      - PORT=9292
      - WORKSPACE=/workspace
      - CNN_POSTGRES={"host":"postgres","port":5432,"user":"northwind","password":"northwind","database":"northwind"}
    volumes:
      - ./workspace:/workspace  
    # Se configuro network mode host por que cuando se intentaba conectar desde este contenedor al postgress, daba error de conexion
    # TODO: configurar nuevamente como network y resolver el problema.
    # network_mode: host
    ports:
      - 9292:9292
      # - 9229:9229 # debug port 
    expose:
      - 9292
      # - 9229 # debug port      
    networks:
      - pentest
    # command:
    #   - node
    #   - "--inspect-brk=0.0.0.0"
    #   - "."   
  prometheus:
    depends_on:
      - orm
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus      
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - pentest
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:7.1.5
    container_name: grafana    
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:      
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana  
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - pentest
volumes:
  prometheus_data: {}
  grafana_data: {}
  postgres-data: {}        
