global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute. 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: "node"
    static_configs:
      - targets: ["orm-svc-pentest_orm_1:9292",
                  "orm-svc-pentest_orm_2:9292",
                  "orm-svc-pentest_orm_3:9292"
                ]  
 