@host = http://localhost:9289

@expression= Orders.filter(p=>p.id==id).include(p=>p.customer)  



GET {{host}}/metadata?exp={{expression}} HTTP/1.1

###
GET {{host}}/model?exp={{expression}} HTTP/1.1

###
GET {{host}}/parameters?exp={{expression}} HTTP/1.1

###
GET {{host}}/sentence?exp={{expression}} HTTP/1.1

###
POST {{host}}/run?exp={{expression}} HTTP/1.1
content-type: application/json

{ 
  "id":"10248"
}