@host = http://localhost:9289

@query= Orders.filter(p=>p.id==id).include(p=>p.customer)  



GET {{host}}/metadata?query={{query}} HTTP/1.1

###
GET {{host}}/model?query={{query}} HTTP/1.1

###
GET {{host}}/parameters?query={{query}} HTTP/1.1

###
GET {{host}}/sentence?query={{query}} HTTP/1.1

###
POST {{host}}/run?query={{query}} HTTP/1.1
content-type: application/json

{ 
  "id":"10248"
}