name: Publish
on:
  push:
    branches: [release/*]
  pull_request:
    branches: [release/*]
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install global dependencies
        run: npm install -g grunt-cli husky
      - name: Install dependencies
        run: npm install
      - name: Build dist
        run: npm run dist
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6        
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/lambdaorm-svc
          tags: ${{ steps.version.outputs.value }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Delete branch
        run: |
          git push origin --delete ${{ github.ref_name }} --no-verify
          echo "Branch ${{ github.ref_name }} deleted"    
