name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: git config --global user.name "FlavioLionelRita"
      - run: git config --global user.email "flaviolrita@gmail.com"
      - run: npm version ${{ github.event.release.tag_name }}
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Build dist
        run: npm run dist
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lambdaorm-svc:${{ github.event.release.tag_name }}
      # push the version changes to GitHub
      - name: Push
        run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GH_TOKEN }}
