name: Release
on:
  push:
    branches: [release/*]
  pull_request:
    branches: [release/*]
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install global dependencies
        run: npm install -g grunt-cli husky standard-version
      - name: Install dependencies
        run: npm install
      - name: Set Version
        run: export VERSION=$(jq -r '.version' ./package.json )
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lambdaorm-svc:${{ env.VERSION }}
